# Generated by Django 4.0.6 on 2023-08-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsfeed_delete_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfeed',
            name='author',
            field=models.TextField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsfeed',
            name='link',
            field=models.URLField(default=False),
            preserve_default=False,
        ),
    ]
