# Generated by Django 4.0.6 on 2023-08-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_movie_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='image',
            new_name='image_file',
        ),
        migrations.AddField(
            model_name='movie',
            name='image_url',
            field=models.URLField(default=False),
            preserve_default=False,
        ),
    ]
