# Generated by Django 4.0.6 on 2023-08-10 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_rename_image_movie_image_file_movie_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='image_file',
        ),
    ]
